[versions]
android-library = "8.13.0"
android-compileSdk = "36"
android-minSdk = "26"
android-namespace = "io.gihub.perawallet"
android-targetSdk = "36"
android-versionCode = "124"
android-versionName = "5.202502.0"
kotlin = "2.1.0"
nmcp = "1.2.0"


[plugins]
android-library = { id = "com.android.library", version.ref = "android-library" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
nmcp = { id = "com.gradleup.nmcp.aggregation", version.ref = "nmcp" }